### ISSUE TITLE
SEO Metadata - GraphQL Support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout#240]
- [ ] https://github.com/barrelstrength/sprout/issues/64
- [ ] https://github.com/barrelstrength/sprout-private/issues/94
- [ ] https://github.com/barrelstrength/sprout-private/issues/79
